<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>net-snmp: example.c Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.7.4 -->
<div id="top">
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td style="padding-left: 0.5em;">
   <div id="projectname">net-snmp&#160;<span id="projectnumber">5.7</span></div>
  </td>
 </tr>
 </tbody>
</table>
</div>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.html"><span>Related&#160;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li><a href="annotated.html"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="files.html"><span>Files</span></a></li>
      <li><a href="examples.html"><span>Examples</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.html"><span>File&#160;List</span></a></li>
      <li><a href="globals.html"><span>Globals</span></a></li>
    </ul>
  </div>
<div class="header">
  <div class="headertitle">
<div class="title">example.c</div>  </div>
</div>
<div class="contents">
<div class="fragment"><pre class="fragment"><a name="l00001"></a>00001 <span class="comment">/*</span>
<a name="l00002"></a>00002 <span class="comment"> *  Template MIB group implementation - example.c</span>
<a name="l00003"></a>00003 <span class="comment"> *</span>
<a name="l00004"></a>00004 <span class="comment"> */</span>
<a name="l00005"></a>00005 
<a name="l00006"></a>00006 <span class="comment">/*</span>
<a name="l00007"></a>00007 <span class="comment"> * include important headers </span>
<a name="l00008"></a>00008 <span class="comment"> */</span>
<a name="l00009"></a>00009 <span class="preprocessor">#include &lt;net-snmp/net-snmp-config.h&gt;</span>
<a name="l00010"></a>00010 <span class="preprocessor">#if HAVE_STDLIB_H</span>
<a name="l00011"></a>00011 <span class="preprocessor"></span><span class="preprocessor">#include &lt;stdlib.h&gt;</span>
<a name="l00012"></a>00012 <span class="preprocessor">#endif</span>
<a name="l00013"></a>00013 <span class="preprocessor"></span><span class="preprocessor">#if HAVE_STRING_H</span>
<a name="l00014"></a>00014 <span class="preprocessor"></span><span class="preprocessor">#include &lt;string.h&gt;</span>
<a name="l00015"></a>00015 <span class="preprocessor">#else</span>
<a name="l00016"></a>00016 <span class="preprocessor"></span><span class="preprocessor">#include &lt;strings.h&gt;</span>
<a name="l00017"></a>00017 <span class="preprocessor">#endif</span>
<a name="l00018"></a>00018 <span class="preprocessor"></span>
<a name="l00019"></a>00019 <span class="preprocessor">#include &lt;net-snmp/net-snmp-includes.h&gt;</span>
<a name="l00020"></a>00020 <span class="preprocessor">#include &lt;net-snmp/agent/net-snmp-agent-includes.h&gt;</span>
<a name="l00021"></a>00021 
<a name="l00022"></a>00022 <span class="comment">/*</span>
<a name="l00023"></a>00023 <span class="comment"> * header_generic() comes from here </span>
<a name="l00024"></a>00024 <span class="comment"> */</span>
<a name="l00025"></a>00025 <span class="preprocessor">#include &quot;util_funcs/header_generic.h&quot;</span>
<a name="l00026"></a>00026 
<a name="l00027"></a>00027 <span class="comment">/*</span>
<a name="l00028"></a>00028 <span class="comment"> * include our .h file </span>
<a name="l00029"></a>00029 <span class="comment"> */</span>
<a name="l00030"></a>00030 <span class="preprocessor">#include &quot;example.h&quot;</span>
<a name="l00031"></a>00031 
<a name="l00032"></a>00032 
<a name="l00033"></a>00033    <span class="comment">/*</span>
<a name="l00034"></a>00034 <span class="comment">    *  Certain objects can be set via configuration file directives.</span>
<a name="l00035"></a>00035 <span class="comment">    *  These variables hold the values for such objects, as they need to</span>
<a name="l00036"></a>00036 <span class="comment">    *   be accessible to both the config handlers, and the callback routine.</span>
<a name="l00037"></a>00037 <span class="comment">    */</span>
<a name="l00038"></a>00038 <span class="preprocessor">#define EXAMPLE_STR_LEN 300</span>
<a name="l00039"></a>00039 <span class="preprocessor"></span><span class="preprocessor">#define EXAMPLE_STR_DEFAULT     &quot;life the universe and everything&quot;</span>
<a name="l00040"></a>00040 <span class="preprocessor"></span><span class="keywordtype">int</span>             example_int = 42;
<a name="l00041"></a>00041 <span class="keywordtype">char</span>            example_str[EXAMPLE_STR_LEN];
<a name="l00042"></a>00042 
<a name="l00043"></a>00043         <span class="comment">/*</span>
<a name="l00044"></a>00044 <span class="comment">         * Forward declarations for the config handlers </span>
<a name="l00045"></a>00045 <span class="comment">         */</span>
<a name="l00046"></a>00046 <span class="keywordtype">void</span>            example_parse_config_exampleint(<span class="keyword">const</span> <span class="keywordtype">char</span> *token,
<a name="l00047"></a>00047                                                 <span class="keywordtype">char</span> *cptr);
<a name="l00048"></a>00048 <span class="keywordtype">void</span>            example_parse_config_examplestr(<span class="keyword">const</span> <span class="keywordtype">char</span> *token,
<a name="l00049"></a>00049                                                 <span class="keywordtype">char</span> *cptr);
<a name="l00050"></a>00050 <span class="keywordtype">void</span>            example_free_config_exampleint(<span class="keywordtype">void</span>);
<a name="l00051"></a>00051 <span class="keywordtype">void</span>            example_free_config_examplestr(<span class="keywordtype">void</span>);
<a name="l00052"></a>00052 
<a name="l00053"></a>00053 
<a name="l00054"></a>00054         <span class="comment">/*********************</span>
<a name="l00055"></a>00055 <span class="comment">         *</span>
<a name="l00056"></a>00056 <span class="comment">         *  Initialisation &amp; common implementation functions</span>
<a name="l00057"></a>00057 <span class="comment">         *</span>
<a name="l00058"></a>00058 <span class="comment">         *********************/</span>
<a name="l00059"></a>00059 
<a name="l00060"></a>00060     <span class="comment">/*</span>
<a name="l00061"></a>00061 <span class="comment">     * This array structure defines a representation of the</span>
<a name="l00062"></a>00062 <span class="comment">     *  MIB being implemented.</span>
<a name="l00063"></a>00063 <span class="comment">     *</span>
<a name="l00064"></a>00064 <span class="comment">     * The type of the array is &#39;struct variableN&#39;, where N is</span>
<a name="l00065"></a>00065 <span class="comment">     *  large enough to contain the longest OID sub-component</span>
<a name="l00066"></a>00066 <span class="comment">     *  being loaded.  This will normally be the maximum value</span>
<a name="l00067"></a>00067 <span class="comment">     *  of the fifth field in each line.  In this case, the second</span>
<a name="l00068"></a>00068 <span class="comment">     *  and third entries are both of size 2, so we&#39;re using</span>
<a name="l00069"></a>00069 <span class="comment">     *  &#39;struct variable2&#39;</span>
<a name="l00070"></a>00070 <span class="comment">     *</span>
<a name="l00071"></a>00071 <span class="comment">     * The supported values for N are listed in &lt;agent/var_struct.h&gt;</span>
<a name="l00072"></a>00072 <span class="comment">     *  If the value you need is not listed there, simply use the</span>
<a name="l00073"></a>00073 <span class="comment">     *  next largest that is.</span>
<a name="l00074"></a>00074 <span class="comment">     *</span>
<a name="l00075"></a>00075 <span class="comment">     * The format of each line is as follows</span>
<a name="l00076"></a>00076 <span class="comment">     *  (using the first entry as an example):</span>
<a name="l00077"></a>00077 <span class="comment">     *      1: EXAMPLESTRING:</span>
<a name="l00078"></a>00078 <span class="comment">     *          The magic number defined in the example header file.</span>
<a name="l00079"></a>00079 <span class="comment">     *          This is passed to the callback routine and is used</span>
<a name="l00080"></a>00080 <span class="comment">     *            to determine which object is being queried.</span>
<a name="l00081"></a>00081 <span class="comment">     *      2: ASN_OCTET_STR:</span>
<a name="l00082"></a>00082 <span class="comment">     *          The type of the object.</span>
<a name="l00083"></a>00083 <span class="comment">     *          Valid types are listed in &lt;snmp_impl.h&gt;</span>
<a name="l00084"></a>00084 <span class="comment">     *      3: NETSNMP_OLDAPI_RONLY (or NETSNMP_OLDAPI_RWRITE):</span>
<a name="l00085"></a>00085 <span class="comment">     *          Whether this object can be SET or not.</span>
<a name="l00086"></a>00086 <span class="comment">     *      4: var_example:</span>
<a name="l00087"></a>00087 <span class="comment">     *          The callback routine, used when the object is queried.</span>
<a name="l00088"></a>00088 <span class="comment">     *          This will usually be the same for all objects in a module</span>
<a name="l00089"></a>00089 <span class="comment">     *            and is typically defined later in this file.</span>
<a name="l00090"></a>00090 <span class="comment">     *      5: 1:</span>
<a name="l00091"></a>00091 <span class="comment">     *          The length of the OID sub-component (the next field)</span>
<a name="l00092"></a>00092 <span class="comment">     *      6: {1}:</span>
<a name="l00093"></a>00093 <span class="comment">     *          The OID sub-components of this entry.</span>
<a name="l00094"></a>00094 <span class="comment">     *          In other words, the bits of the full OID that differ</span>
<a name="l00095"></a>00095 <span class="comment">     *            between the various entries of this array.</span>
<a name="l00096"></a>00096 <span class="comment">     *          This value is appended to the common prefix (defined later)</span>
<a name="l00097"></a>00097 <span class="comment">     *            to obtain the full OID of each entry.</span>
<a name="l00098"></a>00098 <span class="comment">     */</span>
<a name="l00099"></a>00099 <span class="keyword">struct </span><a class="code" href="structvariable2.html">variable2</a> example_variables[] = {
<a name="l00100"></a>00100     {EXAMPLESTRING, ASN_OCTET_STR, NETSNMP_OLDAPI_RONLY,
<a name="l00101"></a>00101      var_example, 1, {1}},
<a name="l00102"></a>00102     {EXAMPLEINTEGER, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
<a name="l00103"></a>00103      var_example, 2, {2, 1}},
<a name="l00104"></a>00104     {EXAMPLEOBJECTID, ASN_OBJECT_ID, NETSNMP_OLDAPI_RONLY,
<a name="l00105"></a>00105      var_example, 2, {2, 2}},
<a name="l00106"></a>00106     {EXAMPLETIMETICKS, ASN_TIMETICKS, NETSNMP_OLDAPI_RONLY,
<a name="l00107"></a>00107      var_example, 1, {3}},
<a name="l00108"></a>00108     {EXAMPLEIPADDRESS, ASN_IPADDRESS, NETSNMP_OLDAPI_RONLY,
<a name="l00109"></a>00109      var_example, 1, {4}},
<a name="l00110"></a>00110     {EXAMPLECOUNTER, ASN_COUNTER, NETSNMP_OLDAPI_RONLY,
<a name="l00111"></a>00111      var_example, 1, {5}},
<a name="l00112"></a>00112     {EXAMPLEGAUGE, ASN_GAUGE, NETSNMP_OLDAPI_RONLY,
<a name="l00113"></a>00113      var_example, 1, {6}},
<a name="l00114"></a>00114     {EXAMPLETRIGGERTRAP, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
<a name="l00115"></a>00115      var_example, 1, {7}},
<a name="l00116"></a>00116     {EXAMPLETRIGGERTRAP2, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
<a name="l00117"></a>00117      var_example, 1, {8}}
<a name="l00118"></a>00118 };
<a name="l00119"></a>00119 
<a name="l00120"></a>00120     <span class="comment">/*</span>
<a name="l00121"></a>00121 <span class="comment">     * This array defines the OID of the top of the mib tree that we&#39;re</span>
<a name="l00122"></a>00122 <span class="comment">     *  registering underneath.</span>
<a name="l00123"></a>00123 <span class="comment">     * Note that this needs to be the correct size for the OID being </span>
<a name="l00124"></a>00124 <span class="comment">     *  registered, so that the length of the OID can be calculated.</span>
<a name="l00125"></a>00125 <span class="comment">     *  The format given here is the simplest way to achieve this.</span>
<a name="l00126"></a>00126 <span class="comment">     */</span>
<a name="l00127"></a>00127 oid             example_variables_oid[] = { 1, 3, 6, 1, 4, 1, 2021, 254 };
<a name="l00128"></a>00128 
<a name="l00129"></a>00129 
<a name="l00130"></a>00130 
<a name="l00131"></a>00131     <span class="comment">/*</span>
<a name="l00132"></a>00132 <span class="comment">     * This function is called at the time the agent starts up</span>
<a name="l00133"></a>00133 <span class="comment">     *  to do any initializations that might be required.</span>
<a name="l00134"></a>00134 <span class="comment">     *</span>
<a name="l00135"></a>00135 <span class="comment">     * In theory it is optional and can be omitted if no</span>
<a name="l00136"></a>00136 <span class="comment">     *  initialization is needed.  In practise, every module</span>
<a name="l00137"></a>00137 <span class="comment">     *  will need to register itself (or the objects being</span>
<a name="l00138"></a>00138 <span class="comment">     *  implemented will not appear in the MIB tree), and this</span>
<a name="l00139"></a>00139 <span class="comment">     *  registration is typically done here.</span>
<a name="l00140"></a>00140 <span class="comment">     *</span>
<a name="l00141"></a>00141 <span class="comment">     * If this function is added or removed, you must re-run</span>
<a name="l00142"></a>00142 <span class="comment">     *  the configure script, to detect this change.</span>
<a name="l00143"></a>00143 <span class="comment">     */</span>
<a name="l00144"></a>00144 <span class="keywordtype">void</span>
<a name="l00145"></a>00145 init_example(<span class="keywordtype">void</span>)
<a name="l00146"></a>00146 {
<a name="l00147"></a>00147     <span class="comment">/*</span>
<a name="l00148"></a>00148 <span class="comment">     * Register ourselves with the agent to handle our mib tree.</span>
<a name="l00149"></a>00149 <span class="comment">     * The arguments are:</span>
<a name="l00150"></a>00150 <span class="comment">     *    descr:   A short description of the mib group being loaded.</span>
<a name="l00151"></a>00151 <span class="comment">     *    var:     The variable structure to load.</span>
<a name="l00152"></a>00152 <span class="comment">     *                  (the name of the variable structure defined above)</span>
<a name="l00153"></a>00153 <span class="comment">     *    vartype: The type of this variable structure</span>
<a name="l00154"></a>00154 <span class="comment">     *    theoid:  The OID pointer this MIB is being registered underneath.</span>
<a name="l00155"></a>00155 <span class="comment">     */</span>
<a name="l00156"></a>00156     REGISTER_MIB(<span class="stringliteral">&quot;example&quot;</span>, example_variables, <a class="code" href="structvariable2.html">variable2</a>,
<a name="l00157"></a>00157                  example_variables_oid);
<a name="l00158"></a>00158 
<a name="l00159"></a>00159 
<a name="l00160"></a>00160     <span class="comment">/*</span>
<a name="l00161"></a>00161 <span class="comment">     *  Register config handlers for the two objects that can be set</span>
<a name="l00162"></a>00162 <span class="comment">     *   via configuration file directive.</span>
<a name="l00163"></a>00163 <span class="comment">     *  Also set a default value for the string object.  Note that the</span>
<a name="l00164"></a>00164 <span class="comment">     *   example integer variable was initialised above.</span>
<a name="l00165"></a>00165 <span class="comment">     */</span>
<a name="l00166"></a>00166     strncpy(example_str, EXAMPLE_STR_DEFAULT, EXAMPLE_STR_LEN);
<a name="l00167"></a>00167 
<a name="l00168"></a>00168     snmpd_register_config_handler(<span class="stringliteral">&quot;exampleint&quot;</span>,
<a name="l00169"></a>00169                                   example_parse_config_exampleint,
<a name="l00170"></a>00170                                   example_free_config_exampleint,
<a name="l00171"></a>00171                                   <span class="stringliteral">&quot;exampleint value&quot;</span>);
<a name="l00172"></a>00172     snmpd_register_config_handler(<span class="stringliteral">&quot;examplestr&quot;</span>,
<a name="l00173"></a>00173                                   example_parse_config_examplestr,
<a name="l00174"></a>00174                                   example_free_config_examplestr,
<a name="l00175"></a>00175                                   <span class="stringliteral">&quot;examplestr value&quot;</span>);
<a name="l00176"></a>00176     snmpd_register_config_handler(<span class="stringliteral">&quot;examplestring&quot;</span>,
<a name="l00177"></a>00177                                   example_parse_config_examplestr,
<a name="l00178"></a>00178                                   example_free_config_examplestr,
<a name="l00179"></a>00179                                   <span class="stringliteral">&quot;examplestring value&quot;</span>);
<a name="l00180"></a>00180 
<a name="l00181"></a>00181     <span class="comment">/*</span>
<a name="l00182"></a>00182 <span class="comment">     * One common requirement is to read values from the kernel.</span>
<a name="l00183"></a>00183 <span class="comment">     * This is usually initialised here, to speed up access when the</span>
<a name="l00184"></a>00184 <span class="comment">     *  information is read in, as a response to an incoming request.</span>
<a name="l00185"></a>00185 <span class="comment">     *</span>
<a name="l00186"></a>00186 <span class="comment">     * This module doesn&#39;t actually use this mechanism,</span>
<a name="l00187"></a>00187 <span class="comment">     * so this call is commented out here.</span>
<a name="l00188"></a>00188 <span class="comment">     */</span>
<a name="l00189"></a>00189     <span class="comment">/*</span>
<a name="l00190"></a>00190 <span class="comment">     * auto_nlist( &quot;example_symbol&quot;, 0, 0 ); </span>
<a name="l00191"></a>00191 <span class="comment">     */</span>
<a name="l00192"></a>00192 }
<a name="l00193"></a>00193 
<a name="l00194"></a>00194         <span class="comment">/*********************</span>
<a name="l00195"></a>00195 <span class="comment">         *</span>
<a name="l00196"></a>00196 <span class="comment">         *  Configuration file handling functions</span>
<a name="l00197"></a>00197 <span class="comment">         *</span>
<a name="l00198"></a>00198 <span class="comment">         *********************/</span>
<a name="l00199"></a>00199 
<a name="l00200"></a>00200 <span class="keywordtype">void</span>
<a name="l00201"></a>00201 example_parse_config_exampleint(<span class="keyword">const</span> <span class="keywordtype">char</span> *token, <span class="keywordtype">char</span> *cptr)
<a name="l00202"></a>00202 {
<a name="l00203"></a>00203     example_int = atoi(cptr);
<a name="l00204"></a>00204 }
<a name="l00205"></a>00205 
<a name="l00206"></a>00206 <span class="keywordtype">void</span>
<a name="l00207"></a>00207 example_parse_config_examplestr(<span class="keyword">const</span> <span class="keywordtype">char</span> *token, <span class="keywordtype">char</span> *cptr)
<a name="l00208"></a>00208 {
<a name="l00209"></a>00209     <span class="comment">/*</span>
<a name="l00210"></a>00210 <span class="comment">     * Make sure the string fits in the space allocated for it.</span>
<a name="l00211"></a>00211 <span class="comment">     */</span>
<a name="l00212"></a>00212     <span class="keywordflow">if</span> (strlen(cptr) &lt; EXAMPLE_STR_LEN)
<a name="l00213"></a>00213         strcpy(example_str, cptr);
<a name="l00214"></a>00214     <span class="keywordflow">else</span> {
<a name="l00215"></a>00215         <span class="comment">/*</span>
<a name="l00216"></a>00216 <span class="comment">         * Truncate the string if necessary.</span>
<a name="l00217"></a>00217 <span class="comment">         * An alternative approach would be to log an error,</span>
<a name="l00218"></a>00218 <span class="comment">         *  and discard this value altogether.</span>
<a name="l00219"></a>00219 <span class="comment">         */</span>
<a name="l00220"></a>00220         strncpy(example_str, cptr, EXAMPLE_STR_LEN - 4);
<a name="l00221"></a>00221         example_str[EXAMPLE_STR_LEN - 4] = 0;
<a name="l00222"></a>00222         strcat(example_str, <span class="stringliteral">&quot;...&quot;</span>);
<a name="l00223"></a>00223         example_str[EXAMPLE_STR_LEN - 1] = 0;
<a name="l00224"></a>00224     }
<a name="l00225"></a>00225 }
<a name="l00226"></a>00226 
<a name="l00227"></a>00227         <span class="comment">/*</span>
<a name="l00228"></a>00228 <span class="comment">         * We don&#39;t need to do anything special when closing down </span>
<a name="l00229"></a>00229 <span class="comment">         */</span>
<a name="l00230"></a>00230 <span class="keywordtype">void</span>
<a name="l00231"></a>00231 example_free_config_exampleint(<span class="keywordtype">void</span>)
<a name="l00232"></a>00232 {
<a name="l00233"></a>00233 }
<a name="l00234"></a>00234 
<a name="l00235"></a>00235 <span class="keywordtype">void</span>
<a name="l00236"></a>00236 example_free_config_examplestr(<span class="keywordtype">void</span>)
<a name="l00237"></a>00237 {
<a name="l00238"></a>00238 }
<a name="l00239"></a>00239 
<a name="l00240"></a>00240         <span class="comment">/*********************</span>
<a name="l00241"></a>00241 <span class="comment">         *</span>
<a name="l00242"></a>00242 <span class="comment">         *  System specific implementation functions</span>
<a name="l00243"></a>00243 <span class="comment">         *</span>
<a name="l00244"></a>00244 <span class="comment">         *********************/</span>
<a name="l00245"></a>00245 
<a name="l00246"></a>00246     <span class="comment">/*</span>
<a name="l00247"></a>00247 <span class="comment">     * Define the callback function used in the example_variables structure.</span>
<a name="l00248"></a>00248 <span class="comment">     * This is called whenever an incoming request refers to an object</span>
<a name="l00249"></a>00249 <span class="comment">     *  within this sub-tree.</span>
<a name="l00250"></a>00250 <span class="comment">     *</span>
<a name="l00251"></a>00251 <span class="comment">     * Four of the parameters are used to pass information in.</span>
<a name="l00252"></a>00252 <span class="comment">     * These are:</span>
<a name="l00253"></a>00253 <span class="comment">     *    vp      The entry from the &#39;example_variables&#39; array for the</span>
<a name="l00254"></a>00254 <span class="comment">     *             object being queried.</span>
<a name="l00255"></a>00255 <span class="comment">     *    name    The OID from the request.</span>
<a name="l00256"></a>00256 <span class="comment">     *    length  The length of this OID.</span>
<a name="l00257"></a>00257 <span class="comment">     *    exact   A flag to indicate whether this is an &#39;exact&#39; request</span>
<a name="l00258"></a>00258 <span class="comment">     *             (GET/SET) or an &#39;inexact&#39; one (GETNEXT/GETBULK).</span>
<a name="l00259"></a>00259 <span class="comment">     *</span>
<a name="l00260"></a>00260 <span class="comment">     * Four of the parameters are used to pass information back out.</span>
<a name="l00261"></a>00261 <span class="comment">     * These are:</span>
<a name="l00262"></a>00262 <span class="comment">     *    name     The OID being returned.</span>
<a name="l00263"></a>00263 <span class="comment">     *    length   The length of this OID.</span>
<a name="l00264"></a>00264 <span class="comment">     *    var_len  The length of the answer being returned.</span>
<a name="l00265"></a>00265 <span class="comment">     *    write_method   A pointer to the SET function for this object.</span>
<a name="l00266"></a>00266 <span class="comment">     *</span>
<a name="l00267"></a>00267 <span class="comment">     * Note that name &amp; length serve a dual purpose in both roles.</span>
<a name="l00268"></a>00268 <span class="comment">     */</span>
<a name="l00269"></a>00269 
<a name="l00270"></a>00270 u_char         *
<a name="l00271"></a>00271 var_example(<span class="keyword">struct</span> <a class="code" href="structvariable.html">variable</a> *vp,
<a name="l00272"></a>00272             oid * name,
<a name="l00273"></a>00273             <span class="keywordtype">size_t</span> * length,
<a name="l00274"></a>00274             <span class="keywordtype">int</span> exact, <span class="keywordtype">size_t</span> * var_len, WriteMethod ** write_method)
<a name="l00275"></a>00275 {
<a name="l00276"></a>00276     <span class="comment">/*</span>
<a name="l00277"></a>00277 <span class="comment">     *  The result returned from this function needs to be a pointer to</span>
<a name="l00278"></a>00278 <span class="comment">     *    static data (so that it can be accessed from outside).</span>
<a name="l00279"></a>00279 <span class="comment">     *  Define suitable variables for any type of data we may return.</span>
<a name="l00280"></a>00280 <span class="comment">     */</span>
<a name="l00281"></a>00281     <span class="keyword">static</span> <span class="keywordtype">char</span>     <span class="keywordtype">string</span>[EXAMPLE_STR_LEN];    <span class="comment">/* for EXAMPLESTRING   */</span>
<a name="l00282"></a>00282     <span class="keyword">static</span> oid      oid_ret[8]; <span class="comment">/* for EXAMPLEOBJECTID */</span>
<a name="l00283"></a>00283     <span class="keyword">static</span> <span class="keywordtype">long</span>     long_ret;   <span class="comment">/* for everything else */</span>
<a name="l00284"></a>00284 
<a name="l00285"></a>00285     <span class="comment">/*</span>
<a name="l00286"></a>00286 <span class="comment">     * Before returning an answer, we need to check that the request</span>
<a name="l00287"></a>00287 <span class="comment">     *  refers to a valid instance of this object.  The utility routine</span>
<a name="l00288"></a>00288 <span class="comment">     *  &#39;header_generic&#39; can be used to do this for scalar objects.</span>
<a name="l00289"></a>00289 <span class="comment">     *</span>
<a name="l00290"></a>00290 <span class="comment">     * This routine &#39;header_simple_table&#39; does the same thing for &quot;simple&quot;</span>
<a name="l00291"></a>00291 <span class="comment">     *  tables. (See the AGENT.txt file for the definition of a simple table).</span>
<a name="l00292"></a>00292 <span class="comment">     *</span>
<a name="l00293"></a>00293 <span class="comment">     * Both these utility routines also set up default values for the</span>
<a name="l00294"></a>00294 <span class="comment">     *  return arguments (assuming the check succeeded).</span>
<a name="l00295"></a>00295 <span class="comment">     * The name and length are set suitably for the current object,</span>
<a name="l00296"></a>00296 <span class="comment">     *  var_len assumes that the result is an integer of some form,</span>
<a name="l00297"></a>00297 <span class="comment">     *  and write_method assumes that the object cannot be set.</span>
<a name="l00298"></a>00298 <span class="comment">     *</span>
<a name="l00299"></a>00299 <span class="comment">     * If these assumptions are correct, this callback routine simply</span>
<a name="l00300"></a>00300 <span class="comment">     * needs to return a pointer to the appropriate value (using &#39;long_ret&#39;).</span>
<a name="l00301"></a>00301 <span class="comment">     * Otherwise, &#39;var_len&#39; and/or &#39;write_method&#39; should be set suitably.</span>
<a name="l00302"></a>00302 <span class="comment">     */</span>
<a name="l00303"></a>00303     DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;var_example entered\n&quot;</span>));
<a name="l00304"></a>00304     <span class="keywordflow">if</span> (header_generic(vp, name, length, exact, var_len, write_method) ==
<a name="l00305"></a>00305         MATCH_FAILED)
<a name="l00306"></a>00306         <span class="keywordflow">return</span> NULL;
<a name="l00307"></a>00307 
<a name="l00308"></a>00308 
<a name="l00309"></a>00309     <span class="comment">/*</span>
<a name="l00310"></a>00310 <span class="comment">     * Many object will need to obtain data from the operating system in</span>
<a name="l00311"></a>00311 <span class="comment">     *  order to return the appropriate value.  Typically, this is done</span>
<a name="l00312"></a>00312 <span class="comment">     *  here - immediately following the &#39;header&#39; call, and before the</span>
<a name="l00313"></a>00313 <span class="comment">     *  switch statement. This is particularly appropriate if a single </span>
<a name="l00314"></a>00314 <span class="comment">     *  interface call can return data for all the objects supported.</span>
<a name="l00315"></a>00315 <span class="comment">     *</span>
<a name="l00316"></a>00316 <span class="comment">     * This example module does not rely on external data, so no such</span>
<a name="l00317"></a>00317 <span class="comment">     *  calls are needed in this case.  </span>
<a name="l00318"></a>00318 <span class="comment">     */</span>
<a name="l00319"></a>00319 
<a name="l00320"></a>00320     <span class="comment">/*</span>
<a name="l00321"></a>00321 <span class="comment">     * Now use the magic number from the variable pointer &#39;vp&#39; to</span>
<a name="l00322"></a>00322 <span class="comment">     *  select the particular object being queried.</span>
<a name="l00323"></a>00323 <span class="comment">     * In each case, one of the static objects is set up with the</span>
<a name="l00324"></a>00324 <span class="comment">     *  appropriate information, and returned mapped to a &#39;u_char *&#39;</span>
<a name="l00325"></a>00325 <span class="comment">     */</span>
<a name="l00326"></a>00326     <span class="keywordflow">switch</span> (vp-&gt;magic) {
<a name="l00327"></a>00327     <span class="keywordflow">case</span> EXAMPLESTRING:
<a name="l00328"></a>00328         strcpy(<span class="keywordtype">string</span>, example_str);
<a name="l00329"></a>00329         <span class="comment">/*</span>
<a name="l00330"></a>00330 <span class="comment">         * Note that the assumption that the answer will be an</span>
<a name="l00331"></a>00331 <span class="comment">         *  integer does not hold true in this case, so the length</span>
<a name="l00332"></a>00332 <span class="comment">         *  of the answer needs to be set explicitly.           </span>
<a name="l00333"></a>00333 <span class="comment">         */</span>
<a name="l00334"></a>00334         *var_len = strlen(<span class="keywordtype">string</span>);
<a name="l00335"></a>00335         <span class="keywordflow">return</span> (u_char *) string;
<a name="l00336"></a>00336 
<a name="l00337"></a>00337     <span class="keywordflow">case</span> EXAMPLEINTEGER:
<a name="l00338"></a>00338         <span class="comment">/*</span>
<a name="l00339"></a>00339 <span class="comment">         * Here the length assumption is correct, but the</span>
<a name="l00340"></a>00340 <span class="comment">         *  object is writeable, so we need to set the</span>
<a name="l00341"></a>00341 <span class="comment">         *  write_method pointer as well as the current value.</span>
<a name="l00342"></a>00342 <span class="comment">         */</span>
<a name="l00343"></a>00343         long_ret = example_int;
<a name="l00344"></a>00344         *write_method = write_exampleint;
<a name="l00345"></a>00345         <span class="keywordflow">return</span> (u_char *) &amp; long_ret;
<a name="l00346"></a>00346 
<a name="l00347"></a>00347     <span class="keywordflow">case</span> EXAMPLEOBJECTID:
<a name="l00348"></a>00348         oid_ret[0] = 1;
<a name="l00349"></a>00349         oid_ret[1] = 3;
<a name="l00350"></a>00350         oid_ret[2] = 6;
<a name="l00351"></a>00351         oid_ret[3] = 1;
<a name="l00352"></a>00352         oid_ret[4] = 4;
<a name="l00353"></a>00353         oid_ret[5] = oid_ret[6] = oid_ret[7] = 42;
<a name="l00354"></a>00354         <span class="comment">/*</span>
<a name="l00355"></a>00355 <span class="comment">         * Again, the assumption regarding the answer length is wrong.</span>
<a name="l00356"></a>00356 <span class="comment">         */</span>
<a name="l00357"></a>00357         *var_len = 8 * <span class="keyword">sizeof</span>(oid);
<a name="l00358"></a>00358         <span class="keywordflow">return</span> (u_char *) oid_ret;
<a name="l00359"></a>00359 
<a name="l00360"></a>00360     <span class="keywordflow">case</span> EXAMPLETIMETICKS:
<a name="l00361"></a>00361         <span class="comment">/*</span>
<a name="l00362"></a>00362 <span class="comment">         * Here both assumptions are correct,</span>
<a name="l00363"></a>00363 <span class="comment">         *  so we just need to set up the answer.</span>
<a name="l00364"></a>00364 <span class="comment">         */</span>
<a name="l00365"></a>00365         long_ret = 363136200;   <span class="comment">/* 42 days, 42 minutes and 42.0 seconds */</span>
<a name="l00366"></a>00366         <span class="keywordflow">return</span> (u_char *) &amp; long_ret;
<a name="l00367"></a>00367 
<a name="l00368"></a>00368     <span class="keywordflow">case</span> EXAMPLEIPADDRESS:
<a name="l00369"></a>00369         <span class="comment">/*</span>
<a name="l00370"></a>00370 <span class="comment">         * ipaddresses get returned as a long.  ick </span>
<a name="l00371"></a>00371 <span class="comment">         */</span>
<a name="l00372"></a>00372         <span class="comment">/*</span>
<a name="l00373"></a>00373 <span class="comment">         * we&#39;re returning 127.0.0.1 </span>
<a name="l00374"></a>00374 <span class="comment">         */</span>
<a name="l00375"></a>00375         long_ret = ntohl(INADDR_LOOPBACK);
<a name="l00376"></a>00376         <span class="keywordflow">return</span> (u_char *) &amp; long_ret;
<a name="l00377"></a>00377 
<a name="l00378"></a>00378     <span class="keywordflow">case</span> EXAMPLECOUNTER:
<a name="l00379"></a>00379         long_ret = 42;
<a name="l00380"></a>00380         <span class="keywordflow">return</span> (u_char *) &amp; long_ret;
<a name="l00381"></a>00381 
<a name="l00382"></a>00382     <span class="keywordflow">case</span> EXAMPLEGAUGE:
<a name="l00383"></a>00383         long_ret = 42;          <span class="comment">/* Do we detect a theme running through these answers? */</span>
<a name="l00384"></a>00384         <span class="keywordflow">return</span> (u_char *) &amp; long_ret;
<a name="l00385"></a>00385 
<a name="l00386"></a>00386     <span class="keywordflow">case</span> EXAMPLETRIGGERTRAP:
<a name="l00387"></a>00387         <span class="comment">/*</span>
<a name="l00388"></a>00388 <span class="comment">         * This object is essentially &quot;write-only&quot;.</span>
<a name="l00389"></a>00389 <span class="comment">         * It only exists to trigger the sending of a trap.</span>
<a name="l00390"></a>00390 <span class="comment">         * Reading it will always return 0.</span>
<a name="l00391"></a>00391 <span class="comment">         */</span>
<a name="l00392"></a>00392         long_ret = 0;
<a name="l00393"></a>00393         *write_method = write_exampletrap;
<a name="l00394"></a>00394         <span class="keywordflow">return</span> (u_char *) &amp; long_ret;
<a name="l00395"></a>00395 
<a name="l00396"></a>00396     <span class="keywordflow">case</span> EXAMPLETRIGGERTRAP2:
<a name="l00397"></a>00397         <span class="comment">/*</span>
<a name="l00398"></a>00398 <span class="comment">         * This object is essentially &quot;write-only&quot;.</span>
<a name="l00399"></a>00399 <span class="comment">         * It only exists to trigger the sending of a v2 trap.</span>
<a name="l00400"></a>00400 <span class="comment">         * Reading it will always return 0.</span>
<a name="l00401"></a>00401 <span class="comment">         */</span>
<a name="l00402"></a>00402         long_ret = 0;
<a name="l00403"></a>00403         *write_method = write_exampletrap2;
<a name="l00404"></a>00404         <span class="keywordflow">return</span> (u_char *) &amp; long_ret;
<a name="l00405"></a>00405 
<a name="l00406"></a>00406     <span class="keywordflow">default</span>:
<a name="l00407"></a>00407         <span class="comment">/*</span>
<a name="l00408"></a>00408 <span class="comment">         *  This will only be triggered if there&#39;s a problem with</span>
<a name="l00409"></a>00409 <span class="comment">         *   the coding of the module.  SNMP requests that reference</span>
<a name="l00410"></a>00410 <span class="comment">         *   a non-existant OID will be directed elsewhere.</span>
<a name="l00411"></a>00411 <span class="comment">         *  If this branch is reached, log an error, so that</span>
<a name="l00412"></a>00412 <span class="comment">         *   the problem can be investigated.</span>
<a name="l00413"></a>00413 <span class="comment">         */</span>
<a name="l00414"></a>00414         DEBUGMSGTL((<span class="stringliteral">&quot;snmpd&quot;</span>, <span class="stringliteral">&quot;unknown sub-id %d in examples/var_example\n&quot;</span>,
<a name="l00415"></a>00415                     vp-&gt;magic));
<a name="l00416"></a>00416     }
<a name="l00417"></a>00417     <span class="comment">/*</span>
<a name="l00418"></a>00418 <span class="comment">     * If we fall through to here, fail by returning NULL.</span>
<a name="l00419"></a>00419 <span class="comment">     * This is essentially a continuation of the &#39;default&#39; case above.</span>
<a name="l00420"></a>00420 <span class="comment">     */</span>
<a name="l00421"></a>00421     <span class="keywordflow">return</span> NULL;
<a name="l00422"></a>00422 }
<a name="l00423"></a>00423 
<a name="l00424"></a>00424         <span class="comment">/*********************</span>
<a name="l00425"></a>00425 <span class="comment">         *</span>
<a name="l00426"></a>00426 <span class="comment">         *  Writeable object SET handling routines</span>
<a name="l00427"></a>00427 <span class="comment">         *</span>
<a name="l00428"></a>00428 <span class="comment">         *********************/</span>
<a name="l00429"></a>00429 <span class="keywordtype">int</span>
<a name="l00430"></a>00430 write_exampleint(<span class="keywordtype">int</span> action,
<a name="l00431"></a>00431                  u_char * var_val,
<a name="l00432"></a>00432                  u_char var_val_type,
<a name="l00433"></a>00433                  <span class="keywordtype">size_t</span> var_val_len,
<a name="l00434"></a>00434                  u_char * statP, oid * name, <span class="keywordtype">size_t</span> name_len)
<a name="l00435"></a>00435 {
<a name="l00436"></a>00436     <span class="comment">/*</span>
<a name="l00437"></a>00437 <span class="comment">     * Define an arbitrary maximum permissible value </span>
<a name="l00438"></a>00438 <span class="comment">     */</span>
<a name="l00439"></a>00439 <span class="preprocessor">#define MAX_EXAMPLE_INT 100</span>
<a name="l00440"></a>00440 <span class="preprocessor"></span>    <span class="keyword">static</span> <span class="keywordtype">long</span>     intval;
<a name="l00441"></a>00441     <span class="keyword">static</span> <span class="keywordtype">long</span>     old_intval;
<a name="l00442"></a>00442 
<a name="l00443"></a>00443     <span class="keywordflow">switch</span> (action) {
<a name="l00444"></a>00444     <span class="keywordflow">case</span> RESERVE1:
<a name="l00445"></a>00445         <span class="comment">/*</span>
<a name="l00446"></a>00446 <span class="comment">         *  Check that the value being set is acceptable</span>
<a name="l00447"></a>00447 <span class="comment">         */</span>
<a name="l00448"></a>00448         <span class="keywordflow">if</span> (var_val_type != ASN_INTEGER) {
<a name="l00449"></a>00449             DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;%x not integer type&quot;</span>, var_val_type));
<a name="l00450"></a>00450             <span class="keywordflow">return</span> SNMP_ERR_WRONGTYPE;
<a name="l00451"></a>00451         }
<a name="l00452"></a>00452         <span class="keywordflow">if</span> (var_val_len &gt; <span class="keyword">sizeof</span>(<span class="keywordtype">long</span>)) {
<a name="l00453"></a>00453             DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;wrong length %&quot;</span> NETSNMP_PRIz <span class="stringliteral">&quot;u&quot;</span>,
<a name="l00454"></a>00454                         var_val_len));
<a name="l00455"></a>00455             <span class="keywordflow">return</span> SNMP_ERR_WRONGLENGTH;
<a name="l00456"></a>00456         }
<a name="l00457"></a>00457 
<a name="l00458"></a>00458         intval = *((<span class="keywordtype">long</span> *) var_val);
<a name="l00459"></a>00459         <span class="keywordflow">if</span> (intval &gt; MAX_EXAMPLE_INT) {
<a name="l00460"></a>00460             DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;wrong value %lx&quot;</span>, intval));
<a name="l00461"></a>00461             <span class="keywordflow">return</span> SNMP_ERR_WRONGVALUE;
<a name="l00462"></a>00462         }
<a name="l00463"></a>00463         <span class="keywordflow">break</span>;
<a name="l00464"></a>00464 
<a name="l00465"></a>00465     <span class="keywordflow">case</span> RESERVE2:
<a name="l00466"></a>00466         <span class="comment">/*</span>
<a name="l00467"></a>00467 <span class="comment">         *  This is conventially where any necesary</span>
<a name="l00468"></a>00468 <span class="comment">         *   resources are allocated (e.g. calls to malloc)</span>
<a name="l00469"></a>00469 <span class="comment">         *  Here, we are using static variables</span>
<a name="l00470"></a>00470 <span class="comment">         *   so don&#39;t need to worry about this.</span>
<a name="l00471"></a>00471 <span class="comment">         */</span>
<a name="l00472"></a>00472         <span class="keywordflow">break</span>;
<a name="l00473"></a>00473 
<a name="l00474"></a>00474     <span class="keywordflow">case</span> FREE:
<a name="l00475"></a>00475         <span class="comment">/*</span>
<a name="l00476"></a>00476 <span class="comment">         *  This is where any of the above resources</span>
<a name="l00477"></a>00477 <span class="comment">         *   are freed again (because one of the other</span>
<a name="l00478"></a>00478 <span class="comment">         *   values being SET failed for some reason).</span>
<a name="l00479"></a>00479 <span class="comment">         *  Again, since we are using static variables</span>
<a name="l00480"></a>00480 <span class="comment">         *   we don&#39;t need to worry about this either.</span>
<a name="l00481"></a>00481 <span class="comment">         */</span>
<a name="l00482"></a>00482         <span class="keywordflow">break</span>;
<a name="l00483"></a>00483 
<a name="l00484"></a>00484     <span class="keywordflow">case</span> ACTION:
<a name="l00485"></a>00485         <span class="comment">/*</span>
<a name="l00486"></a>00486 <span class="comment">         *  Set the variable as requested.</span>
<a name="l00487"></a>00487 <span class="comment">         *   Note that this may need to be reversed,</span>
<a name="l00488"></a>00488 <span class="comment">         *   so save any information needed to do this.</span>
<a name="l00489"></a>00489 <span class="comment">         */</span>
<a name="l00490"></a>00490         old_intval = example_int;
<a name="l00491"></a>00491         example_int = intval;
<a name="l00492"></a>00492         <span class="keywordflow">break</span>;
<a name="l00493"></a>00493 
<a name="l00494"></a>00494     <span class="keywordflow">case</span> UNDO:
<a name="l00495"></a>00495         <span class="comment">/*</span>
<a name="l00496"></a>00496 <span class="comment">         *  Something failed, so re-set the</span>
<a name="l00497"></a>00497 <span class="comment">         *   variable to its previous value</span>
<a name="l00498"></a>00498 <span class="comment">         *  (and free any allocated resources).</span>
<a name="l00499"></a>00499 <span class="comment">         */</span>
<a name="l00500"></a>00500         example_int = old_intval;
<a name="l00501"></a>00501         <span class="keywordflow">break</span>;
<a name="l00502"></a>00502 
<a name="l00503"></a>00503     <span class="keywordflow">case</span> COMMIT:
<a name="l00504"></a>00504         <span class="comment">/*</span>
<a name="l00505"></a>00505 <span class="comment">         *  Everything worked, so we can discard any</span>
<a name="l00506"></a>00506 <span class="comment">         *   saved information, and make the change</span>
<a name="l00507"></a>00507 <span class="comment">         *   permanent (e.g. write to the config file).</span>
<a name="l00508"></a>00508 <span class="comment">         *  We also free any allocated resources.</span>
<a name="l00509"></a>00509 <span class="comment">         *</span>
<a name="l00510"></a>00510 <span class="comment">         *  In this case, there&#39;s nothing to do.</span>
<a name="l00511"></a>00511 <span class="comment">         */</span>
<a name="l00512"></a>00512         <span class="keywordflow">break</span>;
<a name="l00513"></a>00513 
<a name="l00514"></a>00514     }
<a name="l00515"></a>00515     <span class="keywordflow">return</span> SNMP_ERR_NOERROR;
<a name="l00516"></a>00516 }
<a name="l00517"></a>00517 
<a name="l00518"></a>00518 <span class="keywordtype">int</span>
<a name="l00519"></a>00519 write_exampletrap(<span class="keywordtype">int</span> action,
<a name="l00520"></a>00520                   u_char * var_val,
<a name="l00521"></a>00521                   u_char var_val_type,
<a name="l00522"></a>00522                   <span class="keywordtype">size_t</span> var_val_len,
<a name="l00523"></a>00523                   u_char * statP, oid * name, <span class="keywordtype">size_t</span> name_len)
<a name="l00524"></a>00524 {
<a name="l00525"></a>00525     <span class="keywordtype">long</span>            intval;
<a name="l00526"></a>00526 
<a name="l00527"></a>00527     DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;write_exampletrap entered: action=%d\n&quot;</span>,
<a name="l00528"></a>00528                 action));
<a name="l00529"></a>00529     <span class="keywordflow">switch</span> (action) {
<a name="l00530"></a>00530     <span class="keywordflow">case</span> RESERVE1:
<a name="l00531"></a>00531         <span class="comment">/*</span>
<a name="l00532"></a>00532 <span class="comment">         *  The only acceptable value is the integer 1</span>
<a name="l00533"></a>00533 <span class="comment">         */</span>
<a name="l00534"></a>00534         <span class="keywordflow">if</span> (var_val_type != ASN_INTEGER) {
<a name="l00535"></a>00535             DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;%x not integer type&quot;</span>, var_val_type));
<a name="l00536"></a>00536             <span class="keywordflow">return</span> SNMP_ERR_WRONGTYPE;
<a name="l00537"></a>00537         }
<a name="l00538"></a>00538         <span class="keywordflow">if</span> (var_val_len &gt; <span class="keyword">sizeof</span>(<span class="keywordtype">long</span>)) {
<a name="l00539"></a>00539             DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;wrong length %&quot;</span> NETSNMP_PRIz <span class="stringliteral">&quot;u&quot;</span>,
<a name="l00540"></a>00540                         var_val_len));
<a name="l00541"></a>00541             <span class="keywordflow">return</span> SNMP_ERR_WRONGLENGTH;
<a name="l00542"></a>00542         }
<a name="l00543"></a>00543 
<a name="l00544"></a>00544         intval = *((<span class="keywordtype">long</span> *) var_val);
<a name="l00545"></a>00545         <span class="keywordflow">if</span> (intval != 1) {
<a name="l00546"></a>00546             DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;wrong value %lx&quot;</span>, intval));
<a name="l00547"></a>00547             <span class="keywordflow">return</span> SNMP_ERR_WRONGVALUE;
<a name="l00548"></a>00548         }
<a name="l00549"></a>00549         <span class="keywordflow">break</span>;
<a name="l00550"></a>00550 
<a name="l00551"></a>00551     <span class="keywordflow">case</span> RESERVE2:
<a name="l00552"></a>00552         <span class="comment">/*</span>
<a name="l00553"></a>00553 <span class="comment">         * No resources are required.... </span>
<a name="l00554"></a>00554 <span class="comment">         */</span>
<a name="l00555"></a>00555         <span class="keywordflow">break</span>;
<a name="l00556"></a>00556 
<a name="l00557"></a>00557     <span class="keywordflow">case</span> FREE:
<a name="l00558"></a>00558         <span class="comment">/*</span>
<a name="l00559"></a>00559 <span class="comment">         * ... so no resources need be freed </span>
<a name="l00560"></a>00560 <span class="comment">         */</span>
<a name="l00561"></a>00561         <span class="keywordflow">break</span>;
<a name="l00562"></a>00562 
<a name="l00563"></a>00563     <span class="keywordflow">case</span> ACTION:
<a name="l00564"></a>00564         <span class="comment">/*</span>
<a name="l00565"></a>00565 <span class="comment">         *  Having triggered the sending of a trap,</span>
<a name="l00566"></a>00566 <span class="comment">         *   it would be impossible to revoke this,</span>
<a name="l00567"></a>00567 <span class="comment">         *   so we can&#39;t actually invoke the action here.</span>
<a name="l00568"></a>00568 <span class="comment">         */</span>
<a name="l00569"></a>00569         <span class="keywordflow">break</span>;
<a name="l00570"></a>00570 
<a name="l00571"></a>00571     <span class="keywordflow">case</span> UNDO:
<a name="l00572"></a>00572         <span class="comment">/*</span>
<a name="l00573"></a>00573 <span class="comment">         * We haven&#39;t done anything yet,</span>
<a name="l00574"></a>00574 <span class="comment">         * so there&#39;s nothing to undo </span>
<a name="l00575"></a>00575 <span class="comment">         */</span>
<a name="l00576"></a>00576         <span class="keywordflow">break</span>;
<a name="l00577"></a>00577 
<a name="l00578"></a>00578     <span class="keywordflow">case</span> COMMIT:
<a name="l00579"></a>00579         <span class="comment">/*</span>
<a name="l00580"></a>00580 <span class="comment">         *  Everything else worked, so it&#39;s now safe</span>
<a name="l00581"></a>00581 <span class="comment">         *   to trigger the trap.</span>
<a name="l00582"></a>00582 <span class="comment">         *  Note that this is *only* acceptable since</span>
<a name="l00583"></a>00583 <span class="comment">         *   the trap sending routines are &quot;failsafe&quot;.</span>
<a name="l00584"></a>00584 <span class="comment">         *  (In fact, they can fail, but they return no</span>
<a name="l00585"></a>00585 <span class="comment">         *   indication of this, which is the next best thing!)</span>
<a name="l00586"></a>00586 <span class="comment">         */</span>
<a name="l00587"></a>00587         DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;write_exampletrap sending the trap\n&quot;</span>));
<a name="l00588"></a>00588         <a class="code" href="group__agent__trap.html#ga86b1bcdaed1156316838acd02a276dc8" title="Sends an SNMPv1 trap (or the SNMPv2 equivalent) to the list of configured trap destinations (or &quot;sink...">send_easy_trap</a>(SNMP_TRAP_ENTERPRISESPECIFIC, 99);
<a name="l00589"></a>00589         DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;write_exampletrap trap sent\n&quot;</span>));
<a name="l00590"></a>00590         <span class="keywordflow">break</span>;
<a name="l00591"></a>00591 
<a name="l00592"></a>00592     }
<a name="l00593"></a>00593     <span class="keywordflow">return</span> SNMP_ERR_NOERROR;
<a name="l00594"></a>00594 }
<a name="l00595"></a>00595 
<a name="l00596"></a>00596 <span class="comment">/*</span>
<a name="l00597"></a>00597 <span class="comment"> * this documents how to send a SNMPv2 (and higher) trap via the</span>
<a name="l00598"></a>00598 <span class="comment"> * send_v2trap() API.</span>
<a name="l00599"></a>00599 <span class="comment"> * </span>
<a name="l00600"></a>00600 <span class="comment"> * Coding SNMP-v2 Trap:</span>
<a name="l00601"></a>00601 <span class="comment"> * </span>
<a name="l00602"></a>00602 <span class="comment"> * The SNMPv2-Trap PDU contains at least a pair of object names and</span>
<a name="l00603"></a>00603 <span class="comment"> * values: - sysUpTime.0 whose value is the time in hundredths of a</span>
<a name="l00604"></a>00604 <span class="comment"> * second since the netwok management portion of system was last</span>
<a name="l00605"></a>00605 <span class="comment"> * reinitialized.  - snmpTrapOID.0 which is part of the trap group SNMPv2</span>
<a name="l00606"></a>00606 <span class="comment"> * MIB whose value is the object-id of the specific trap you have defined</span>
<a name="l00607"></a>00607 <span class="comment"> * in your own MIB.  Other variables can be added to caracterize the</span>
<a name="l00608"></a>00608 <span class="comment"> * trap.</span>
<a name="l00609"></a>00609 <span class="comment"> * </span>
<a name="l00610"></a>00610 <span class="comment"> * The function send_v2trap adds automaticallys the two objects but the</span>
<a name="l00611"></a>00611 <span class="comment"> * value of snmpTrapOID.0 is 0.0 by default. If you want to add your trap</span>
<a name="l00612"></a>00612 <span class="comment"> * name, you have to reconstruct this object and to add your own</span>
<a name="l00613"></a>00613 <span class="comment"> * variable.</span>
<a name="l00614"></a>00614 <span class="comment"> * </span>
<a name="l00615"></a>00615 <span class="comment"> */</span>
<a name="l00616"></a>00616 
<a name="l00617"></a>00617 
<a name="l00618"></a>00618 
<a name="l00619"></a>00619 <span class="keywordtype">int</span>
<a name="l00620"></a>00620 write_exampletrap2(<span class="keywordtype">int</span> action,
<a name="l00621"></a>00621                    u_char * var_val,
<a name="l00622"></a>00622                    u_char var_val_type,
<a name="l00623"></a>00623                    <span class="keywordtype">size_t</span> var_val_len,
<a name="l00624"></a>00624                    u_char * statP, oid * name, <span class="keywordtype">size_t</span> name_len)
<a name="l00625"></a>00625 {
<a name="l00626"></a>00626     <span class="keywordtype">long</span>            intval;
<a name="l00627"></a>00627 
<a name="l00628"></a>00628     <span class="comment">/*</span>
<a name="l00629"></a>00629 <span class="comment">     * these variales will be used when we send the trap </span>
<a name="l00630"></a>00630 <span class="comment">     */</span>
<a name="l00631"></a>00631     oid             objid_snmptrap[] = { 1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0 };     <span class="comment">/* snmpTrapOID.0 */</span>
<a name="l00632"></a>00632     oid             demo_trap[] = { 1, 3, 6, 1, 4, 1, 2021, 13, 990 };  <span class="comment">/*demo-trap */</span>
<a name="l00633"></a>00633     oid             example_string_oid[] =
<a name="l00634"></a>00634         { 1, 3, 6, 1, 4, 1, 2021, 254, 1, 0 };
<a name="l00635"></a>00635     <span class="keyword">static</span> <a class="code" href="structvariable__list.html" title="The netsnmp variable list binding structure, it&#39;s typedef&#39;d to netsnmp_variable_list.">netsnmp_variable_list</a> var_trap;
<a name="l00636"></a>00636     <span class="keyword">static</span> <a class="code" href="structvariable__list.html" title="The netsnmp variable list binding structure, it&#39;s typedef&#39;d to netsnmp_variable_list.">netsnmp_variable_list</a> var_obj;
<a name="l00637"></a>00637 
<a name="l00638"></a>00638     DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;write_exampletrap2 entered: action=%d\n&quot;</span>,
<a name="l00639"></a>00639                 action));
<a name="l00640"></a>00640     <span class="keywordflow">switch</span> (action) {
<a name="l00641"></a>00641     <span class="keywordflow">case</span> RESERVE1:
<a name="l00642"></a>00642         <span class="comment">/*</span>
<a name="l00643"></a>00643 <span class="comment">         *  The only acceptable value is the integer 1</span>
<a name="l00644"></a>00644 <span class="comment">         */</span>
<a name="l00645"></a>00645         <span class="keywordflow">if</span> (var_val_type != ASN_INTEGER) {
<a name="l00646"></a>00646             DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;%x not integer type&quot;</span>, var_val_type));
<a name="l00647"></a>00647             <span class="keywordflow">return</span> SNMP_ERR_WRONGTYPE;
<a name="l00648"></a>00648         }
<a name="l00649"></a>00649         <span class="keywordflow">if</span> (var_val_len &gt; <span class="keyword">sizeof</span>(<span class="keywordtype">long</span>)) {
<a name="l00650"></a>00650             DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;wrong length %&quot;</span> NETSNMP_PRIz <span class="stringliteral">&quot;u&quot;</span>,
<a name="l00651"></a>00651                         var_val_len));
<a name="l00652"></a>00652             <span class="keywordflow">return</span> SNMP_ERR_WRONGLENGTH;
<a name="l00653"></a>00653         }
<a name="l00654"></a>00654 
<a name="l00655"></a>00655         intval = *((<span class="keywordtype">long</span> *) var_val);
<a name="l00656"></a>00656         <span class="keywordflow">if</span> (intval != 1) {
<a name="l00657"></a>00657             DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;wrong value %lx&quot;</span>, intval));
<a name="l00658"></a>00658             <span class="keywordflow">return</span> SNMP_ERR_WRONGVALUE;
<a name="l00659"></a>00659         }
<a name="l00660"></a>00660         <span class="keywordflow">break</span>;
<a name="l00661"></a>00661 
<a name="l00662"></a>00662     <span class="keywordflow">case</span> RESERVE2:
<a name="l00663"></a>00663         <span class="comment">/*</span>
<a name="l00664"></a>00664 <span class="comment">         * No resources are required.... </span>
<a name="l00665"></a>00665 <span class="comment">         */</span>
<a name="l00666"></a>00666         <span class="keywordflow">break</span>;
<a name="l00667"></a>00667 
<a name="l00668"></a>00668     <span class="keywordflow">case</span> FREE:
<a name="l00669"></a>00669         <span class="comment">/*</span>
<a name="l00670"></a>00670 <span class="comment">         * ... so no resources need be freed </span>
<a name="l00671"></a>00671 <span class="comment">         */</span>
<a name="l00672"></a>00672         <span class="keywordflow">break</span>;
<a name="l00673"></a>00673 
<a name="l00674"></a>00674     <span class="keywordflow">case</span> ACTION:
<a name="l00675"></a>00675         <span class="comment">/*</span>
<a name="l00676"></a>00676 <span class="comment">         *  Having triggered the sending of a trap,</span>
<a name="l00677"></a>00677 <span class="comment">         *   it would be impossible to revoke this,</span>
<a name="l00678"></a>00678 <span class="comment">         *   so we can&#39;t actually invoke the action here.</span>
<a name="l00679"></a>00679 <span class="comment">         */</span>
<a name="l00680"></a>00680         <span class="keywordflow">break</span>;
<a name="l00681"></a>00681 
<a name="l00682"></a>00682     <span class="keywordflow">case</span> UNDO:
<a name="l00683"></a>00683         <span class="comment">/*</span>
<a name="l00684"></a>00684 <span class="comment">         * We haven&#39;t done anything yet,</span>
<a name="l00685"></a>00685 <span class="comment">         * so there&#39;s nothing to undo </span>
<a name="l00686"></a>00686 <span class="comment">         */</span>
<a name="l00687"></a>00687         <span class="keywordflow">break</span>;
<a name="l00688"></a>00688 
<a name="l00689"></a>00689     <span class="keywordflow">case</span> COMMIT:
<a name="l00690"></a>00690         <span class="comment">/*</span>
<a name="l00691"></a>00691 <span class="comment">         *  Everything else worked, so it&#39;s now safe</span>
<a name="l00692"></a>00692 <span class="comment">         *   to trigger the trap.</span>
<a name="l00693"></a>00693 <span class="comment">         *  Note that this is *only* acceptable since</span>
<a name="l00694"></a>00694 <span class="comment">         *   the trap sending routines are &quot;failsafe&quot;.</span>
<a name="l00695"></a>00695 <span class="comment">         *  (In fact, they can fail, but they return no</span>
<a name="l00696"></a>00696 <span class="comment">         *   indication of this, which is the next best thing!)</span>
<a name="l00697"></a>00697 <span class="comment">         */</span>
<a name="l00698"></a>00698 
<a name="l00699"></a>00699         <span class="comment">/*</span>
<a name="l00700"></a>00700 <span class="comment">         * trap definition objects </span>
<a name="l00701"></a>00701 <span class="comment">         */</span>
<a name="l00702"></a>00702 
<a name="l00703"></a>00703         var_trap.<a class="code" href="structvariable__list.html#a036af3c8c73da042622a58afa452d76e" title="NULL for last variable.">next_variable</a> = &amp;var_obj;      <span class="comment">/* next variable */</span>
<a name="l00704"></a>00704         var_trap.<a class="code" href="structvariable__list.html#a7b5bdda01921550d24ea53033ce76146" title="Object identifier of variable.">name</a> = objid_snmptrap; <span class="comment">/* snmpTrapOID.0 */</span>
<a name="l00705"></a>00705         var_trap.<a class="code" href="structvariable__list.html#a089e5b1a422bf8e693510ff5408a57a7" title="number of subid&#39;s in name">name_length</a> = <span class="keyword">sizeof</span>(objid_snmptrap) / <span class="keyword">sizeof</span>(oid);    <span class="comment">/* number of sub-ids */</span>
<a name="l00706"></a>00706         var_trap.<a class="code" href="structvariable__list.html#a8bd719974b3554116631ea80dc88b6aa" title="ASN type of variable.">type</a> = ASN_OBJECT_ID;
<a name="l00707"></a>00707         var_trap.<a class="code" href="structvariable__list.html#a6ed7c00d712b83c174823b1cff6e9e29" title="value of variable">val</a>.objid = demo_trap; <span class="comment">/* demo-trap objid */</span>
<a name="l00708"></a>00708         var_trap.<a class="code" href="structvariable__list.html#a17aaa6b445178fc39aba69642247d3e9" title="the length of the value to be copied into buf">val_len</a> = <span class="keyword">sizeof</span>(demo_trap);   <span class="comment">/* length in bytes (not number of subids!) */</span>
<a name="l00709"></a>00709 
<a name="l00710"></a>00710 
<a name="l00711"></a>00711         <span class="comment">/*</span>
<a name="l00712"></a>00712 <span class="comment">         * additional objects </span>
<a name="l00713"></a>00713 <span class="comment">         */</span>
<a name="l00714"></a>00714 
<a name="l00715"></a>00715 
<a name="l00716"></a>00716         var_obj.<a class="code" href="structvariable__list.html#a036af3c8c73da042622a58afa452d76e" title="NULL for last variable.">next_variable</a> = NULL;   <span class="comment">/* No more variables after this one */</span>
<a name="l00717"></a>00717         var_obj.<a class="code" href="structvariable__list.html#a7b5bdda01921550d24ea53033ce76146" title="Object identifier of variable.">name</a> = example_string_oid;
<a name="l00718"></a>00718         var_obj.<a class="code" href="structvariable__list.html#a089e5b1a422bf8e693510ff5408a57a7" title="number of subid&#39;s in name">name_length</a> = <span class="keyword">sizeof</span>(example_string_oid) / <span class="keyword">sizeof</span>(oid); <span class="comment">/* number of sub-ids */</span>
<a name="l00719"></a>00719         var_obj.<a class="code" href="structvariable__list.html#a8bd719974b3554116631ea80dc88b6aa" title="ASN type of variable.">type</a> = ASN_OCTET_STR;   <span class="comment">/* type of variable */</span>
<a name="l00720"></a>00720         var_obj.<a class="code" href="structvariable__list.html#a6ed7c00d712b83c174823b1cff6e9e29" title="value of variable">val</a>.string = (<span class="keywordtype">unsigned</span> <span class="keywordtype">char</span> *) example_str;       <span class="comment">/* value */</span>
<a name="l00721"></a>00721         var_obj.<a class="code" href="structvariable__list.html#a17aaa6b445178fc39aba69642247d3e9" title="the length of the value to be copied into buf">val_len</a> = strlen(example_str);
<a name="l00722"></a>00722         DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;write_exampletrap2 sending the v2 trap\n&quot;</span>));
<a name="l00723"></a>00723         <a class="code" href="group__agent__trap.html#gac9fa0228d574f715b60cd93b87968a15" title="Uses the supplied list of variable bindings to form an SNMPv2 trap, which is sent to SNMPv2-capable s...">send_v2trap</a>(&amp;var_trap);
<a name="l00724"></a>00724         DEBUGMSGTL((<span class="stringliteral">&quot;example&quot;</span>, <span class="stringliteral">&quot;write_exampletrap2 v2 trap sent\n&quot;</span>));
<a name="l00725"></a>00725 
<a name="l00726"></a>00726         <span class="keywordflow">break</span>;
<a name="l00727"></a>00727 
<a name="l00728"></a>00728     }
<a name="l00729"></a>00729     <span class="keywordflow">return</span> SNMP_ERR_NOERROR;
<a name="l00730"></a>00730 }
</pre></div></div>
</div>
<hr class="footer"/><address class="footer"><small>Generated on Thu Jul 14 2011 for net-snmp by&#160;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.7.4 </small></address>
</body>
</html>
